export const projects = [
  {
    id: 1,
    title: "AI Resume Builder",
    description: "An intelligent resume builder that uses GPT-4 to generate tailored resumes based on job descriptions. Features real-time suggestions, ATS optimization, and PDF export functionality.",
    technologies: "React, Node.js, OpenAI API, MongoDB, TailwindCSS",
    link: "https://github.com/example/ai-resume-builder",
    startDate: "2024-01-01",
    endDate: "2024-03-01",
    photos: [],
  },
  {
    id: 2,
    title: "E-Commerce Platform",
    description: "A full-stack e-commerce platform with product management, cart, checkout, Stripe payments, and admin dashboard. Supports multi-vendor and real-time inventory tracking.",
    technologies: "Next.js, Stripe, PostgreSQL, Prisma, TailwindCSS",
    link: "https://github.com/example/ecommerce-platform",
    startDate: "2023-06-01",
    endDate: "2023-12-01",
    photos: [],
  },
  {
    id: 3,
    title: "Real-Time Chat App",
    description: "A real-time messaging application with rooms, direct messages, emoji reactions, file sharing, and read receipts. Built with WebSockets for instant communication.",
    technologies: "React, Socket.io, Express, MongoDB, JWT",
    link: "https://github.com/example/chat-app",
    startDate: "2023-03-01",
    endDate: "2023-06-01",
    photos: [],
  },
  {
    id: 4,
    title: "Healthcare Dashboard",
    description: "A comprehensive healthcare management dashboard for hospitals with patient records, appointment scheduling, billing, and analytics. HIPAA compliant data handling.",
    technologies: "React, TypeScript, Node.js, PostgreSQL, Chart.js",
    link: "https://github.com/example/healthcare-dashboard",
    startDate: "2023-09-01",
    endDate: "2024-02-01",
    photos: [],
  },
  {
    id: 5,
    title: "Crypto Portfolio Tracker",
    description: "Track your cryptocurrency portfolio in real-time with live price feeds, profit/loss calculations, historical charts, and price alerts via email and SMS.",
    technologies: "React, CoinGecko API, Firebase, Recharts, TailwindCSS",
    link: "https://github.com/example/crypto-tracker",
    startDate: "2023-11-01",
    endDate: "2024-01-01",
    photos: [],
  },
  {
    id: 6,
    title: "Social Media Analytics",
    description: "An analytics platform for social media managers to track engagement, follower growth, post performance, and competitor analysis across multiple platforms.",
    technologies: "Vue.js, Python, FastAPI, PostgreSQL, D3.js",
    link: "https://github.com/example/social-analytics",
    startDate: "2023-07-01",
    endDate: "2023-11-01",
    photos: [],
  },
  {
    id: 7,
    title: "Food Delivery App",
    description: "A mobile-first food delivery application with real-time order tracking, restaurant discovery, review system, and driver management portal.",
    technologies: "React Native, Node.js, MongoDB, Google Maps API, Stripe",
    link: "https://github.com/example/food-delivery",
    startDate: "2023-04-01",
    endDate: "2023-09-01",
    photos: [],
  },
  {
    id: 8,
    title: "DevOps Monitoring Tool",
    description: "A DevOps monitoring platform that aggregates logs, tracks server metrics, sends alerts, and provides deployment pipelines visualization.",
    technologies: "React, Prometheus, Grafana, Docker, Kubernetes, Go",
    link: "https://github.com/example/devops-monitor",
    startDate: "2024-02-01",
    endDate: "2024-05-01",
    photos: [],
  },
  {
    id: 9,
    title: "Online Learning Platform",
    description: "An EdTech platform with video courses, quizzes, certificates, progress tracking, live sessions, and instructor dashboards. Supports 10,000+ concurrent users.",
    technologies: "Next.js, AWS S3, PostgreSQL, Redis, Stripe, WebRTC",
    link: "https://github.com/example/learning-platform",
    startDate: "2023-01-01",
    endDate: "2023-08-01",
    photos: [],
  },
  {
    id: 10,
    title: "Smart Home Automation",
    description: "IoT-based smart home system to control lights, temperature, security cameras, and appliances via a mobile app and voice commands.",
    technologies: "React Native, MQTT, Raspberry Pi, Python, Firebase",
    link: "https://github.com/example/smart-home",
    startDate: "2023-05-01",
    endDate: "2023-10-01",
    photos: [],
  },
  {
    id: 11,
    title: "Job Board Platform",
    description: "A job listing platform with company profiles, applicant tracking system, resume parser, skill matching algorithm, and email notifications.",
    technologies: "React, Node.js, Elasticsearch, PostgreSQL, Redis",
    link: "https://github.com/example/job-board",
    startDate: "2023-08-01",
    endDate: "2024-01-01",
    photos: [],
  },
  {
    id: 12,
    title: "Expense Tracker",
    description: "Personal finance app to track expenses, set budgets, categorize spending, generate reports, and sync with bank accounts via Plaid API.",
    technologies: "React, Plaid API, Node.js, MongoDB, Chart.js",
    link: "https://github.com/example/expense-tracker",
    startDate: "2023-02-01",
    endDate: "2023-05-01",
    photos: [],
  },
  {
    id: 13,
    title: "Code Review Tool",
    description: "A collaborative code review platform with inline comments, PR management, automated code analysis, and integration with GitHub and GitLab.",
    technologies: "React, TypeScript, GraphQL, PostgreSQL, Docker",
    link: "https://github.com/example/code-review",
    startDate: "2024-03-01",
    endDate: "2024-06-01",
    photos: [],
  },
  {
    id: 14,
    title: "NFT Marketplace",
    description: "A decentralized NFT marketplace for minting, buying, and selling digital art with wallet integration, royalty management, and auction features.",
    technologies: "React, Solidity, Web3.js, IPFS, Hardhat, Ethereum",
    link: "https://github.com/example/nft-marketplace",
    startDate: "2023-10-01",
    endDate: "2024-02-01",
    photos: [],
  },
  {
    id: 15,
    title: "Travel Planner App",
    description: "AI-powered travel planning app that generates itineraries, books hotels and flights, tracks expenses, and provides offline maps and guides.",
    technologies: "React Native, GPT-4, Google Maps, Skyscanner API, Firebase",
    link: "https://github.com/example/travel-planner",
    startDate: "2023-12-01",
    endDate: "2024-04-01",
    photos: [],
  },
  {
    id: 16,
    title: "Video Streaming Platform",
    description: "Netflix-like video streaming platform with adaptive bitrate streaming, content recommendation, subscription management, and multi-device support.",
    technologies: "React, AWS CloudFront, FFmpeg, Node.js, PostgreSQL",
    link: "https://github.com/example/video-streaming",
    startDate: "2023-03-01",
    endDate: "2023-10-01",
    photos: [],
  },
  {
    id: 17,
    title: "HR Management System",
    description: "Complete HR solution covering recruitment, onboarding, payroll, leave management, performance reviews, and employee self-service portal.",
    technologies: "Angular, Java Spring Boot, MySQL, Redis, Docker",
    link: "https://github.com/example/hr-system",
    startDate: "2022-11-01",
    endDate: "2023-07-01",
    photos: [],
  },
  {
    id: 18,
    title: "Fitness Tracking App",
    description: "Workout tracking app with exercise library, custom routines, progress charts, calorie calculator, and integration with wearables like Apple Watch.",
    technologies: "React Native, HealthKit, Firebase, Node.js, MongoDB",
    link: "https://github.com/example/fitness-tracker",
    startDate: "2023-06-01",
    endDate: "2023-09-01",
    photos: [],
  },
  {
    id: 19,
    title: "Project Management Tool",
    description: "Jira-like project management tool with kanban boards, sprint planning, time tracking, burndown charts, and Slack/GitHub integrations.",
    technologies: "React, TypeScript, Node.js, PostgreSQL, WebSockets",
    link: "https://github.com/example/project-management",
    startDate: "2022-09-01",
    endDate: "2023-03-01",
    photos: [],
  },
  {
    id: 20,
    title: "Weather Forecast App",
    description: "Beautiful weather app with 7-day forecasts, hourly data, radar maps, severe weather alerts, and location-based automatic updates.",
    technologies: "React, OpenWeather API, Mapbox, TailwindCSS, PWA",
    link: "https://github.com/example/weather-app",
    startDate: "2023-01-01",
    endDate: "2023-03-01",
    photos: [],
  },
  {
    id: 21,
    title: "Inventory Management System",
    description: "Warehouse inventory system with barcode scanning, stock alerts, supplier management, purchase orders, and real-time reporting dashboard.",
    technologies: "React, Node.js, PostgreSQL, Redis, Docker, Chart.js",
    link: "https://github.com/example/inventory-system",
    startDate: "2023-04-01",
    endDate: "2023-08-01",
    photos: [],
  },
  {
    id: 22,
    title: "Language Learning App",
    description: "Duolingo-style language learning app with spaced repetition, speech recognition, gamification, leaderboards, and 20+ supported languages.",
    technologies: "React Native, Python, TensorFlow, Firebase, PostgreSQL",
    link: "https://github.com/example/language-app",
    startDate: "2023-07-01",
    endDate: "2023-12-01",
    photos: [],
  },
  {
    id: 23,
    title: "Music Streaming App",
    description: "Spotify-like music streaming platform with playlist management, artist pages, lyrics display, offline mode, and collaborative playlists.",
    technologies: "React, Node.js, AWS S3, PostgreSQL, Redis, WebAudio API",
    link: "https://github.com/example/music-streaming",
    startDate: "2022-12-01",
    endDate: "2023-06-01",
    photos: [],
  },
  {
    id: 24,
    title: "Document Collaboration Tool",
    description: "Google Docs-like real-time document editor with collaborative editing, version history, comments, templates, and export to PDF/DOCX.",
    technologies: "React, Quill.js, CRDTs, Node.js, MongoDB, WebSockets",
    link: "https://github.com/example/doc-collaboration",
    startDate: "2023-09-01",
    endDate: "2024-01-01",
    photos: [],
  },
  {
    id: 25,
    title: "Event Management Platform",
    description: "End-to-end event management solution for creating, promoting, and managing events with ticketing, check-in, sponsorship, and analytics.",
    technologies: "Next.js, Stripe, QR Code, PostgreSQL, SendGrid",
    link: "https://github.com/example/event-platform",
    startDate: "2023-05-01",
    endDate: "2023-09-01",
    photos: [],
  },
  {
    id: 26,
    title: "Stock Market Simulator",
    description: "Paper trading platform for practicing stock trading with real market data, portfolio analytics, risk metrics, and educational resources.",
    technologies: "React, Python, Alpaca API, PostgreSQL, Chart.js",
    link: "https://github.com/example/stock-simulator",
    startDate: "2023-11-01",
    endDate: "2024-02-01",
    photos: [],
  },
  {
    id: 27,
    title: "CRM System",
    description: "Customer Relationship Management system with contact management, deal pipeline, email integration, activity tracking, and sales forecasting.",
    technologies: "React, TypeScript, Node.js, PostgreSQL, Redis, ElasticSearch",
    link: "https://github.com/example/crm-system",
    startDate: "2022-08-01",
    endDate: "2023-02-01",
    photos: [],
  },
  {
    id: 28,
    title: "Blog Platform",
    description: "Medium-like blogging platform with rich text editor, tags, claps, reading lists, newsletter, monetization, and SEO optimization.",
    technologies: "Next.js, MDX, PostgreSQL, Prisma, TailwindCSS, Vercel",
    link: "https://github.com/example/blog-platform",
    startDate: "2023-02-01",
    endDate: "2023-05-01",
    photos: [],
  },
  {
    id: 29,
    title: "AR Navigation App",
    description: "Augmented reality indoor navigation app for malls and airports using ARKit, computer vision, and real-time wayfinding algorithms.",
    technologies: "Swift, ARKit, CoreML, Firebase, Node.js",
    link: "https://github.com/example/ar-navigation",
    startDate: "2024-01-01",
    endDate: "2024-05-01",
    photos: [],
  },
  {
    id: 30,
    title: "Online Voting System",
    description: "Secure blockchain-based voting platform with voter verification, anonymous ballots, real-time results, audit trail, and fraud detection.",
    technologies: "React, Solidity, Ethereum, Node.js, PostgreSQL",
    link: "https://github.com/example/voting-system",
    startDate: "2023-08-01",
    endDate: "2023-12-01",
    photos: [],
  },
  {
    id: 31,
    title: "Recipe Sharing Platform",
    description: "Social cooking platform where users share recipes, create meal plans, generate shopping lists, and watch step-by-step video tutorials.",
    technologies: "React, Node.js, MongoDB, Cloudinary, AWS S3",
    link: "https://github.com/example/recipe-platform",
    startDate: "2023-03-01",
    endDate: "2023-06-01",
    photos: [],
  },
  {
    id: 32,
    title: "Legal Document Analyzer",
    description: "AI-powered legal document analysis tool that extracts key clauses, identifies risks, summarizes contracts, and flags unusual terms.",
    technologies: "Python, GPT-4, FastAPI, React, PostgreSQL, LangChain",
    link: "https://github.com/example/legal-analyzer",
    startDate: "2024-02-01",
    endDate: "2024-06-01",
    photos: [],
  },
  {
    id: 33,
    title: "Supply Chain Tracker",
    description: "Blockchain-based supply chain transparency platform tracking products from manufacturer to consumer with real-time updates and fraud prevention.",
    technologies: "React, Hyperledger Fabric, Node.js, MongoDB, Docker",
    link: "https://github.com/example/supply-chain",
    startDate: "2023-06-01",
    endDate: "2023-11-01",
    photos: [],
  },
  {
    id: 34,
    title: "Mental Health App",
    description: "Meditation and mental wellness app with guided sessions, mood tracking, CBT exercises, therapist matching, and crisis support resources.",
    technologies: "React Native, Firebase, Node.js, PostgreSQL, TensorFlow",
    link: "https://github.com/example/mental-health-app",
    startDate: "2023-10-01",
    endDate: "2024-03-01",
    photos: [],
  },
  {
    id: 35,
    title: "Cloud Storage Service",
    description: "Dropbox-like cloud storage with file sharing, version history, collaboration, automatic sync, and end-to-end encryption.",
    technologies: "React, Go, AWS S3, PostgreSQL, Redis, gRPC",
    link: "https://github.com/example/cloud-storage",
    startDate: "2022-10-01",
    endDate: "2023-04-01",
    photos: [],
  },
  {
    id: 36,
    title: "Booking Management System",
    description: "Multi-purpose booking system for hotels, salons, and clinics with calendar management, automated reminders, payment processing, and reviews.",
    technologies: "React, Node.js, PostgreSQL, Twilio, Stripe, Google Calendar API",
    link: "https://github.com/example/booking-system",
    startDate: "2023-04-01",
    endDate: "2023-08-01",
    photos: [],
  },
  {
    id: 37,
    title: "News Aggregator",
    description: "Personalized news aggregator using ML to learn user preferences, filter misinformation, and deliver curated content from 500+ sources.",
    technologies: "React, Python, scikit-learn, FastAPI, PostgreSQL, Redis",
    link: "https://github.com/example/news-aggregator",
    startDate: "2023-07-01",
    endDate: "2023-10-01",
    photos: [],
  },
  {
    id: 38,
    title: "Parking Management App",
    description: "Smart parking solution with real-time slot availability, reservation, navigation to spots, and automated billing with license plate recognition.",
    technologies: "React Native, Python, OpenCV, Node.js, PostgreSQL",
    link: "https://github.com/example/parking-app",
    startDate: "2023-09-01",
    endDate: "2024-01-01",
    photos: [],
  },
  {
    id: 39,
    title: "Portfolio Website Builder",
    description: "Drag-and-drop portfolio website builder for developers and designers with templates, custom domains, analytics, and one-click deployment.",
    technologies: "React, Next.js, AWS, MongoDB, TailwindCSS, Vercel",
    link: "https://github.com/example/portfolio-builder",
    startDate: "2023-12-01",
    endDate: "2024-03-01",
    photos: [],
  },
  {
    id: 40,
    title: "Telemedicine Platform",
    description: "HIPAA-compliant telemedicine platform with video consultations, e-prescriptions, patient records, insurance verification, and pharmacy integration.",
    technologies: "React, WebRTC, Node.js, PostgreSQL, Twilio, AWS",
    link: "https://github.com/example/telemedicine",
    startDate: "2023-01-01",
    endDate: "2023-09-01",
    photos: [],
  },
  {
    id: 41,
    title: "Ride Sharing App",
    description: "Uber-like ride sharing platform with real-time driver tracking, dynamic pricing, ride scheduling, safety features, and driver earnings dashboard.",
    technologies: "React Native, Node.js, Google Maps, PostgreSQL, Redis, Socket.io",
    link: "https://github.com/example/ride-sharing",
    startDate: "2022-07-01",
    endDate: "2023-01-01",
    photos: [],
  },
  {
    id: 42,
    title: "Smart Agriculture System",
    description: "IoT-based precision agriculture system monitoring soil moisture, temperature, crop health via drones, and automating irrigation systems.",
    technologies: "Python, Arduino, React, MQTT, TensorFlow, Firebase",
    link: "https://github.com/example/smart-agriculture",
    startDate: "2023-05-01",
    endDate: "2023-10-01",
    photos: [],
  },
  {
    id: 43,
    title: "Peer-to-Peer Lending Platform",
    description: "Fintech platform connecting borrowers and lenders with credit scoring, loan management, automated repayments, and investor portfolios.",
    technologies: "React, Node.js, PostgreSQL, Stripe, Python, ML",
    link: "https://github.com/example/p2p-lending",
    startDate: "2023-08-01",
    endDate: "2024-02-01",
    photos: [],
  },
  {
    id: 44,
    title: "Game Streaming Platform",
    description: "Twitch-like game streaming platform with live chat, subscriptions, clip creation, channel points, and streamer analytics dashboard.",
    technologies: "React, WebRTC, Node.js, Redis, FFmpeg, PostgreSQL",
    link: "https://github.com/example/game-streaming",
    startDate: "2023-11-01",
    endDate: "2024-04-01",
    photos: [],
  },
  {
    id: 45,
    title: "Interview Prep Platform",
    description: "Coding interview preparation platform with 2000+ problems, mock interviews, AI feedback on solutions, company-specific tracks, and peer matching.",
    technologies: "React, Node.js, Python, PostgreSQL, Docker, Redis",
    link: "https://github.com/example/interview-prep",
    startDate: "2023-02-01",
    endDate: "2023-07-01",
    photos: [],
  },
  {
    id: 46,
    title: "Waste Management System",
    description: "Smart city waste management platform with IoT sensors in bins, optimized collection routes, recycling tracking, and citizen reporting app.",
    technologies: "React, IoT, Python, Node.js, MongoDB, Google Maps",
    link: "https://github.com/example/waste-management",
    startDate: "2023-06-01",
    endDate: "2023-11-01",
    photos: [],
  },
  {
    id: 47,
    title: "Digital Wallet App",
    description: "Multi-currency digital wallet with P2P transfers, bill payments, QR code payments, transaction history, and fraud detection system.",
    technologies: "React Native, Node.js, PostgreSQL, Redis, Stripe, Plaid",
    link: "https://github.com/example/digital-wallet",
    startDate: "2023-09-01",
    endDate: "2024-02-01",
    photos: [],
  },
  {
    id: 48,
    title: "AI Image Generator",
    description: "Creative AI image generation tool using Stable Diffusion with prompt engineering, style transfer, image editing, and gallery sharing features.",
    technologies: "React, Python, Stable Diffusion, FastAPI, AWS S3, PostgreSQL",
    link: "https://github.com/example/ai-image-generator",
    startDate: "2024-01-01",
    endDate: "2024-04-01",
    photos: [],
  },
  {
    id: 49,
    title: "School Management System",
    description: "Comprehensive school ERP with student enrollment, attendance, gradebook, timetable, fee management, parent portal, and report cards.",
    technologies: "React, Java Spring Boot, MySQL, Redis, Docker",
    link: "https://github.com/example/school-management",
    startDate: "2022-06-01",
    endDate: "2023-01-01",
    photos: [],
  },
  {
    id: 50,
    title: "Carbon Footprint Tracker",
    description: "Personal and corporate carbon footprint tracking app with emission calculations, reduction suggestions, offset purchasing, and sustainability reports.",
    technologies: "React, Node.js, PostgreSQL, Chart.js, TailwindCSS, OpenAI",
    link: "https://github.com/example/carbon-tracker",
    startDate: "2024-03-01",
    endDate: "2024-06-01",
    photos: [],
  },
];